-- 코드를 작성해주세요
WITH VIEWER AS (
    SELECT FISH_TYPE, count(FISH_TYPE) AS FISH_COUNT
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT A.FISH_COUNT, B.FISH_NAME
FROM VIEWER AS A
    LEFT OUTER JOIN FISH_NAME_INFO AS B
    ON A.FISH_TYPE = B.FISH_TYPE
ORDER BY A.FISH_COUNT DESC